name: Example Workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run example action
        id: example_action_step
        uses: gabrielvega-a/github-actions-test@main
        with:
          input1: 'Input 1 value'
          input2: 'Input 2 value'
      
      - name: Display output
        run: echo "Output 1 ${{ steps.example_action_step.outputs.output1 }}"
